//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestEntityFrameworks
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tbl_Control_Item> tbl_Control_Item { get; set; }
        public DbSet<tbl_Control_Item_Atribute_Value> tbl_Control_Item_Atribute_Value { get; set; }
        public DbSet<tbl_DataSource> tbl_DataSource { get; set; }
        public DbSet<tbl_DynamicColumnObject> tbl_DynamicColumnObject { get; set; }
        public DbSet<tbl_DynamicObject> tbl_DynamicObject { get; set; }
        public DbSet<tbl_DynamicObject_DynamicColumn_Value> tbl_DynamicObject_DynamicColumn_Value { get; set; }
        public DbSet<tbl_Form_TableColumn_ControlMapping> tbl_Form_TableColumn_ControlMapping { get; set; }
        public DbSet<tbl_Form_TableColumn_ControlMapping_Label> tbl_Form_TableColumn_ControlMapping_Label { get; set; }
        public DbSet<tbl_FormManager> tbl_FormManager { get; set; }
        public DbSet<tbl_Language> tbl_Language { get; set; }
        public DbSet<tbl_WebForm_Common_Atribute> tbl_WebForm_Common_Atribute { get; set; }
    }
}
