//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestEntityFrameworks
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Control_Item
    {
        public tbl_Control_Item()
        {
            this.tbl_Form_TableColumn_ControlMapping = new HashSet<tbl_Form_TableColumn_ControlMapping>();
        }
    
        public int id { get; set; }
        public string ControlName { get; set; }
        public bool HasDataSource { get; set; }
        public bool OnlyForeignKey { get; set; }
    
        public virtual ICollection<tbl_Form_TableColumn_ControlMapping> tbl_Form_TableColumn_ControlMapping { get; set; }
    }
}
