//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestEntityFrameworks
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Language
    {
        public tbl_Language()
        {
            this.tbl_Form_TableColumn_ControlMapping_Label = new HashSet<tbl_Form_TableColumn_ControlMapping_Label>();
        }
    
        public int id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<tbl_Form_TableColumn_ControlMapping_Label> tbl_Form_TableColumn_ControlMapping_Label { get; set; }
    }
}
