//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestEntityFrameworks
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_WebForm_Common_Atribute
    {
        public tbl_WebForm_Common_Atribute()
        {
            this.tbl_Control_Item_Atribute_Value = new HashSet<tbl_Control_Item_Atribute_Value>();
        }
    
        public int id { get; set; }
        public string NameOfAtribute { get; set; }
        public short Type { get; set; }
        public Nullable<int> Datasource { get; set; }
    
        public virtual ICollection<tbl_Control_Item_Atribute_Value> tbl_Control_Item_Atribute_Value { get; set; }
        public virtual tbl_DataSource tbl_DataSource { get; set; }
    }
}
