//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestEntityFrameworks
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_DynamicObject
    {
        public tbl_DynamicObject()
        {
            this.tbl_DataSource = new HashSet<tbl_DataSource>();
            this.tbl_DynamicObject_DynamicColumn_Value = new HashSet<tbl_DynamicObject_DynamicColumn_Value>();
        }
    
        public int id { get; set; }
        public string ObjectName { get; set; }
    
        public virtual ICollection<tbl_DataSource> tbl_DataSource { get; set; }
        public virtual ICollection<tbl_DynamicObject_DynamicColumn_Value> tbl_DynamicObject_DynamicColumn_Value { get; set; }
    }
}
