//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestEntityFrameworks
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Form_TableColumn_ControlMapping
    {
        public tbl_Form_TableColumn_ControlMapping()
        {
            this.tbl_Control_Item_Atribute_Value = new HashSet<tbl_Control_Item_Atribute_Value>();
            this.tbl_Form_TableColumn_ControlMapping_Label = new HashSet<tbl_Form_TableColumn_ControlMapping_Label>();
        }
    
        public int id { get; set; }
        public int FormItem { get; set; }
        public string TableColumnName { get; set; }
        public Nullable<int> ControlItem { get; set; }
        public Nullable<bool> IsForeignKey { get; set; }
    
        public virtual tbl_Control_Item tbl_Control_Item { get; set; }
        public virtual ICollection<tbl_Control_Item_Atribute_Value> tbl_Control_Item_Atribute_Value { get; set; }
        public virtual ICollection<tbl_Form_TableColumn_ControlMapping_Label> tbl_Form_TableColumn_ControlMapping_Label { get; set; }
        public virtual tbl_FormManager tbl_FormManager { get; set; }
    }
}
