//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestEntityFrameworks
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Form_TableColumn_ControlMapping_Label
    {
        public int FormTableColumnControlMappingItem { get; set; }
        public int LanguageItem { get; set; }
        public string Label { get; set; }
    
        public virtual tbl_Form_TableColumn_ControlMapping tbl_Form_TableColumn_ControlMapping { get; set; }
        public virtual tbl_Language tbl_Language { get; set; }
    }
}
