<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="columndefine.aspx.cs" Inherits="DynamicDataManipulator.WebModuleControl.DynamicData.ColumnDefine" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="frmMain" runat="server">
    <div>
    
                        <asp:Label ID="lbMessage" runat="server" Text="Label"></asp:Label>
                    <table style="width:100%;">
                        <tr>
                            <td>Tên cột</td>
                            <td>:</td>
                            <td>
                                <asp:TextBox ID="txtColumnName" runat="server" MaxLength="500"></asp:TextBox>
                            </td>
                        </tr>
                        <tr>
                            <td>Kiểu dữ liệu</td>
                            <td>:</td>
                            <td>
                                <asp:DropDownList ID="ddlDataType" runat="server">
                                </asp:DropDownList>
                            </td>
                        </tr>
                        <tr>
                            <td>&nbsp;</td>
                            <td>&nbsp;</td>
                            <td>&nbsp;</td>
                        </tr>
        </table>
        <br />
        <br />
        <br />
        <asp:Button ID="btnInsert" runat="server" OnClick="btnInsert_Click" Text="Thêm mới" />
        <br />
    
    </div>
        <asp:GridView ID="grdview" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" OnRowCancelingEdit="grdview_RowCancelingEdit" OnRowEditing="grdview_RowEditing">
            <Columns>
                <asp:TemplateField HeaderText="">
                    <ItemTemplate>
                        <asp:Label runat="server" ID="lbId" Text='<%#Eval("Id")%>'></asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="Đối tượng">
                    <ItemTemplate>
                        <asp:Label runat="server" ID="lbItem" Text='<%#Eval("ObjectColumnName")%>'></asp:Label>
                    </ItemTemplate>
                    <EditItemTemplate>
                        <asp:TextBox runat="server" ID="txtItem" Text='<%#Eval("ObjectColumnName")%>'></asp:TextBox>
                    </EditItemTemplate>
                </asp:TemplateField>
            </Columns>
        </asp:GridView>
    </form>
</body>
</html>
